name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Windows
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      
      - name: Build
        run: cargo build --release
      
      - name: Package
        run: |
          cd target/release
          7z a ../../ergo-vanitygen-windows-amd64.zip ergo-vanitygen.exe
      
      - name: Upload binary to release
        uses: softprops/action-gh-release@v1
        with:
          files: ergo-vanitygen-windows-amd64.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}